"""Deploy content at the hostname generated by CloudFront."""

import aws_cdk as cdk

from aws_cdk_static_site import StaticSite, StaticSiteProps

app = cdk.App()
stack = cdk.Stack(app, 'CloudFrontDomainExample')
site = StaticSite(
    stack,
    'Site',
    props=StaticSiteProps(site_content_path='examples/basic/site'),
)
cdk.CfnOutput(
    stack,
    'DistributionDomainName',
    value=site.distribution.distribution_domain_name,
)
app.synth()
